#!/bin/sh /etc/rc.common

START=90
STOP=10
USE_PROCD=1

PROG=/usr/sbin/wol-proxy
NAME=wol-proxy

start_service() {
	local enabled bind_addr port ifname broadcast allow verbose

	config_load "${NAME}"
	config_get_bool enabled config enabled 1
	[ "${enabled}" -eq 0 ] && return 1

	config_get bind_addr config bind_addr '0.0.0.0'
	config_get port config port '9'
	config_get ifname config ifname 'eth0'
	config_get broadcast config broadcast ''
	config_get allow config allow '0.0.0.0/0'
	config_get_bool verbose config verbose 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_append_param command -b "$bind_addr"
	procd_append_param command -p "$port"
	procd_append_param command -i "$ifname"
	procd_append_param command -a "$allow"
	[ "${verbose}" -eq 1 ] && procd_append_param command -v
	[ -n "$broadcast" ] && procd_append_param command -B "$broadcast"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "${NAME}"
}
