include $(TOPDIR)/rules.mk

LUCI_TITLE:=App Traffic Analyzer - Application & Website Identification
LUCI_DEPENDS:=+luci-compat +apptraffic

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
