server.modules = (
    "mod_auth",
    "mod_authn_file",
    "mod_alias",
    "mod_accesslog",
    "mod_dirlisting",
    "mod_indexfile",
    "mod_cgi",
    "mod_staticfile",
    "mod_openssl",
    "mod_webdav"
)

server.document-root        = "/var/www"
server.upload-dirs          = ( "/tmp" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/var/run/lighttpd.pid"
server.username             = "http"
server.groupname            = "www-data"

index-file.names            = ( "index.html" )
dir-listing.activate        = "disable"

server.bind                 = "10.10.10.1"
server.port                 = 8080

$SERVER["socket"] == "192.168.100.1:8080" {
}

$SERVER["socket"] == "10.10.10.1:8443" {
    ssl.engine = "enable"
    ssl.pemfile = "/etc/lighttpd/server.pem"
}

$SERVER["socket"] == "0.0.0.0:80" {
}

$SERVER["socket"] == "[::]:80" {
}

$SERVER["socket"] == "0.0.0.0:443" {
    ssl.engine = "enable"
    ssl.pemfile = "/etc/lighttpd/server.pem"
}

$SERVER["socket"] == "[::]:443" {
    ssl.engine = "enable"
    ssl.pemfile = "/etc/lighttpd/server.pem"
}

alias.url += ( "/dav/" => "/mnt/sd/", "/dav" => "/mnt/sd/" )
alias.url += ( "/cgi-bin/" => "/usr/lib/cgi-bin/" )

cgi.assign = ( ".cgi" => "" )

$HTTP["url"] =~ "^/dav($|/)" {
    webdav.activate = "enable"
}

accesslog.filename           = "/var/log/lighttpd/access.log"

auth.backend                 = "htpasswd"
auth.backend.htpasswd.userfile = "/etc/lighttpd/webdav.passwd"
auth.require = ( "/dav/" => (
    "method"  => "basic",
    "realm"   => "Cloud",
    "require" => "user=backup"
),
    "/dav" => (
    "method"  => "basic",
    "realm"   => "Cloud",
    "require" => "user=backup"
),
    "/cgi-bin/dav-bridge.cgi" => (
    "method"  => "basic",
    "realm"   => "Cloud",
    "require" => "user=backup"
) )

include "/etc/lighttpd/mime.conf"
